import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: "#f8f8f8",
    },
    header: {
      backgroundColor: "#008080",
      padding: 15,
      paddingTop: 40,
    },
    headerTitle: {
      color: "#fff",
      fontSize: 22,
      textAlign: "center",
      fontFamily: "Poppins_600SemiBold",
    },
    expenseItem: {
      flexDirection: "row",
      justifyContent: "space-between",
      padding: 15,
      borderBottomWidth: 1,
      borderBottomColor: "#ddd",
      backgroundColor: "#fff",
    },
    paidExpense: {
      backgroundColor: "#e0ffe0",
    },
    expenseName: {
      fontSize: 16,
      fontFamily: "Poppins_600SemiBold",
    },
    expenseDate: {
      fontSize: 14,
      color: "#666",
      fontFamily: "Poppins_400Regular",
    },
    expenseRepeat: {
      fontSize: 14,
      color: "#666",
      fontFamily: "Poppins_400Regular",
    },
    expenseAmount: {
      fontSize: 16,
      fontFamily: "Poppins_600SemiBold",
      textAlign: "right",
    },
    paidText: {
      fontSize: 12,
      color: "#34C759",
      fontFamily: "Poppins_400Regular",
    },
    footer: {
      backgroundColor: "#008080",
      padding: 15,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    footerTextContainer: {
      flex: 1,
    },
    footerText: {
      color: "#fff",
      fontSize: 16,
      fontFamily: "Poppins_400Regular",
    },
    footerAmount: {
      color: "#fff",
      fontSize: 16,
      fontFamily: "Poppins_600SemiBold",
    },
    addButton: {
      position: "absolute",
      bottom: 20,
      right: 20,
      backgroundColor: "#FF9800",
      width: 60,
      height: 60,
      borderRadius: 30,
      justifyContent: "center",
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.8,
      shadowRadius: 2,
      elevation: 5,
    },
    modalBackground: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(0, 0, 0, 0.5)",
    },
    modalView: {
      margin: 20,
      backgroundColor: "#fff",
      borderRadius: 10,
      padding: 20,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
      width: "90%",
    },
    modalTitle: {
      fontSize: 20,
      fontFamily: "Poppins_600SemiBold",
      marginBottom: 15,
      textAlign: "center",
    },
    input: {
      height: 40,
      borderColor: "#ddd",
      borderWidth: 1,
      borderRadius: 8,
      paddingHorizontal: 8,
      marginBottom: 16,
      backgroundColor: "#fff",
      fontSize: 16,
      fontFamily: "Poppins_400Regular",
    },
    errorText: {
      color: "#FF3B30",
      marginBottom: 16,
      fontSize: 14,
      fontFamily: "Poppins_400Regular",
    },
    datePickerButton: {
      height: 40,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      borderRadius: 8,
      borderColor: "#ddd",
      borderWidth: 1,
      paddingHorizontal: 8,
      marginBottom: 16,
      backgroundColor: "#fff",
    },
    calendarIcon: {
      marginLeft: 10,
    },
    datePickerText: {
      fontSize: 16,
      color: "#333",
      flex: 1,
    },
    switchContainer: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 16,
      width: "100%",
    },
    label: {
      fontSize: 16,
      fontFamily: "Poppins_400Regular",
      color: "#333",
    },
    switch: {
      transform: [{ scaleX: 1.2 }, { scaleY: 1.2 }],
    },
    modalButtons: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginTop: 20,
      width: "100%",
    },
    modalButton: {
      flex: 1,
      backgroundColor: "#008080",
      padding: 15,
      borderRadius: 8,
      justifyContent: "center",
      alignItems: "center",
      marginHorizontal: 5,
    },
    modalCancelButton: {
      backgroundColor: "#dc3333",
    },
    modalButtonText: {
      color: "#fff",
      fontSize: 16,
      fontFamily: "Poppins_600SemiBold",
    },
    modalCancelButtonText: {
      color: "#fff",
    },
    optionButton: {
      padding: 15,
      borderRadius: 8,
      backgroundColor: "#008080",
      marginVertical: 5,
      justifyContent: "center",
      alignItems: "center",
    },
    optionButtonText: {
      color: "#fff",
      fontSize: 16,
      fontFamily: "Poppins_600SemiBold",
    },
    cancelButton: {
      backgroundColor: "#dc3333",
    },
    dateNav: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      marginVertical: 1,
      position: "relative",
    },
    dateNavBackground: {
      backgroundColor: "#008080",
      paddingVertical: 15,
      paddingHorizontal: 40,
      width: "100%",
    },
    dateText: {
      color: "#fff",
      fontSize: 18,
      fontFamily: "Poppins_600SemiBold",
    },
    dateButtonLeft: {
      position: "absolute",
      left: 10,
    },
    dateButtonRight: {
      position: "absolute",
      right: 10,
    }
  });